[package]
name = "typesxml"
version = "0.1.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { "version" = "4.2.6", features = ["derive"] }
from_file = "0.1.3"
quick-xml = { version = "0.29.0", features = ["serialize"] }
serde = { version = "1.0.164", features = ["derive"] }
write-to-file = "1.0.2"
